## ベクトル

In [1]:
import numpy as np

In [2]:
# ベクトルを定義
a = np.array([2, 1])
a

array([2, 1])

In [3]:
type(a)

numpy.ndarray

In [5]:
# 縦ベクトル
c = np.array([[1, 2], [3, 4]])
c

array([[1, 2],
       [3, 4]])

In [6]:
d = np.array([[1], [2]])
d

array([[1],
       [2]])

In [7]:
# 転置
d.T

array([[1, 2]])

In [9]:
d.T.T  # => 転置を２回繰り返すことで元に戻る

array([[1],
       [2]])

In [10]:
# 足し算と引き算
b = np.array([1, 3])
a + b

array([3, 4])

In [11]:
a - b

array([ 1, -2])

In [12]:
# スカラーとの掛け算
2 * a

array([4, 2])

In [14]:
# 内積
b = np.array([1, 3])
c = np.array([4, 2])
b.dot(c)

10

In [16]:
# 二次元ベクトルの大きさ
a = np.array([1, 3])
np.linalg.norm(a)

3.1622776601683795